{
 "title": "Demo Site - SCB1200",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "content": "<img src=\"public/img/logo.png\" height=\"35\" alt=\"womaster\">"
  },
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 8, "x": 4, "y": 0 } },
  { "title": "CO2 Alarm", "type": "tq-alarm-panel", "gridPos": { "h": 2, "w": 8, "x": 12, "y": 0 } },
  { "title": "Voice Switch", "type": "switch-button-panel", "gridPos": { "h": 2, "w": 3, "x": 20, "y": 0 } },
  { "title": "Site List", "type": "dashlist", "gridPos": { "h": 10, "w": 4, "x": 0, "y": 2 } },
  { "title": "Camera Setting", "type": "camera-control-panel", "gridPos": { "h": 1, "w": 10, "x": 4, "y": 2 } },
  {
   "title": "CO2",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 2 },
   "format": "ppm",
   "valueName": "current",
   "targets": [
    {
     "channel": {
      "text": "select channel",
      "value": null
     },
     "feed": {
      "text": "select feed",
      "value": null
     },
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},\n {\"$project\" :   {  \"name\" : \"CO2\",   \"value\" : \"$CO2\",  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 2 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "channel": {
      "text": "select channel",
      "value": null
     },
     "feed": {
      "text": "select feed",
      "value": null
     },
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},\n {\"$project\" :   {  \"name\" : \"Humidity\",   \"value\" : { \"$divide\": [ \"$Humidity\" , 10 ]},  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 2 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "channel": {
      "text": "select channel",
      "value": null
     },
     "feed": {
      "text": "select feed",
      "value": null
     },
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}}, \n {\"$project\" :   {  \"name\" : \"Temperature\",    \"value\" :  { \"$divide\": [ \"$Temperature\" , 10 ]},  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Video Stream",
   "type": "text",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 3 },
   "content": "<!DOCTYPE html>\n    <html>\n    <title>RTSP Player Page</title>\n        <style type=\"text/css\">\n            body, html\n            {\n                margin: 0; padding: 0; height: 100%; overflow: hidden;\n            }\n\n            #content\n            {\n                position:absolute; left: 0; right: 0; bottom: 0; top: 0px; \n            }\n        </style>\n    <body>\n        <div id=\"content\">\n            <iframe width=\"100%\" height=\"100%\" frameborder=\"0\" src=\"./public/plugins/wom-datasource/video2/index.html?ip=192.168.10.102\" />\n        </div>\n</body>\n</html>"
  },
  {
   "title": "PM1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 9 },
   "format": "conμgm3",
   "valueName": "current",
   "targets": [
    {
     "channel": {
      "text": "select channel",
      "value": null
     },
     "feed": {
      "text": "select feed",
      "value": null
     },
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},\n {\"$project\" :   {  \"name\" : \"PM1\",   \"value\" : \"$PM1\",  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 9 },
   "format": "conμgm3",
   "valueName": "current",
   "targets": [
    {
     "channel": {
      "text": "select channel",
      "value": null
     },
     "feed": {
      "text": "select feed",
      "value": null
     },
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},\n {\"$project\" :   {  \"name\" : \"PM2.5\",   \"value\" : \"$PM2_5\",  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "PM10",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 9 },
   "format": "conμgm3",
   "valueName": "current",
   "targets": [
    {
     "channel": {
      "text": "select channel",
      "value": null
     },
     "feed": {
      "text": "select feed",
      "value": null
     },
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},\n {\"$project\" :   {  \"name\" : \"PM10\",   \"value\" : \"$PM10\",  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "channel": {
      "text": "select channel",
      "value": null
     },
     "feed": {
      "text": "select feed",
      "value": null
     },
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},      \n {\"$project\" :   {  \"name\" : \"CO2\",   \"value\" : \"$CO2\",  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    },
    {
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},\n {\"$project\" :   {  \"name\" : \"Temperature\",    \"value\" :  { \"$divide\": [ \"$Temperature\" , 10 ]},  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    },
    {
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},\n {\"$project\" :   {  \"name\" : \"Humidity\",   \"value\" : { \"$divide\": [ \"$Humidity\" , 10 ]},  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Air Pollution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "channel": {
      "text": "select channel",
      "value": null
     },
     "feed": {
      "text": "select feed",
      "value": null
     },
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},\n {\"$project\" :   {  \"name\" : \"PM1\",   \"value\" : \"$PM1\",  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    },
    {
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},  \n {\"$project\" :   {  \"name\" : \"PM2.5\",   \"value\" : \"$PM2_5\",  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    },
    {
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},     \n {\"$project\" :   {  \"name\" : \"PM10\",   \"value\" : \"$PM10\",  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CO2 Per/10s Count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "channel": {
      "text": "select channel",
      "value": null
     },
     "feed": {
      "text": "select feed",
      "value": null
     },
     "target": "db.data.aggregate ( [ \n { \"$match\" : { \"$and\" : [  { \"start\" :  {\"$gte\" : \"$from\", \"$lte\" : \"$to\"},   \"end\" :  {\"$lte\" : \"$to\"} }, {  \"IPADD\" : \"192.168.10.1\"} ]}},\n {\"$project\" :   {  \"name\" : \"CO2\",   \"value\" : \"$CO2\",  \"at\" : \"$at\",  \"_id\" : 0} } ])",
     "type": "timeserie"
    }
   ]
  }
 ]
}